### ISSUE TITLE
ERROR: File 16x16/start-here-solus-mono.png does not exist

### ISSUE THREAD

**Issue by greyltc** [getsolus/artwork#5]
```
$ meson --prefix /usr build
The Meson build system
Version: 0.56.0
Source dir: /mnt/scratch/git/solus-artwork-git/src/artwork
Build dir: /mnt/scratch/git/solus-artwork-git/src/artwork/build
Build type: native build
Project name: artwork
Project version: 27
C compiler for the host machine: ccache cc (gcc 10.2.0 "cc (GCC) 10.2.0")
C linker for the host machine: cc ld.bfd 2.35.1
Host machine cpu family: x86_64
Host machine cpu: x86_64
Configuring solus-wallpapers.xml using configuration
Configuring solus-wallpapers-mate.xml using configuration

icons/meson.build:28:4: ERROR: File 16x16/start-here-solus-mono.png does not exist.

A full log can be found at /mnt/scratch/git/solus-artwork-git/src/artwork/build/meson-logs/meson-log.txt
```
Am I building it wrong?

**Comment by JoshStrobl** [comment]
It's a regression from f2b29d39ff1b4568383d12fdbae2fa1807ce7c43 by @Girtablulu as he only added scalable and not PNGs for the icon sizes. Not sure why you're building our artwork though.

**Comment by greyltc** [comment]
> Not sure why you're building our artwork though smile  

I was building it to put on my non-solus-running computer. I read the readme and understood that's an okay thing to do.  
Though the readme was a bit confusing to me in parts. What license are `IMG_9656.png`, `IMG_9710.png` and `Excl_*.jpg` provided under?

**Comment by JoshStrobl** [comment]
Many pictures are licensed for distribution to Solus specifically. Going to assist on helping you violating licensing.
